### ISSUE TITLE
Unreachable MinIO share file URL

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#6847]
The MinIO app cannot generate a reachable share file URL from the MinIO console UI.

**Steps to reproduce**

- Install and configure minio 1.0.2
- Access the minio web console
- Create a bucket, upload a file to it
- In the file actions, select "Share"

**Expected behavior**

MinIO generates a share link with the same host name assigned to its web console, or its api.

**Actual behavior**

The share link points to `http://127.0.0.1:9000`, unreachable from internet.

![Image](https://github.com/NethServer/dev/assets/2920838/6f715481-d36f-4d96-b1f3-73d958c4013d)

**Components**

- minio:1.0.2

**See also**

See https://community.nethserver.org/t/ns8-rc1-minio-share-link-poitning-to-localhost-domain/22691

----

Thanks to @compgeniuses for reporting it

**Comment by stephdl** [comment]
one clue is that we do not listen on the 443: https://github.com/minio/minio/issues/13639#issuecomment-966244704

**Comment by compgeniuses** [comment]
YEs, i have a simple minio server setup behind traefik that uses the following compose settings

```
services:
  minio:
    image: 'quay.io/minio/minio:latest'
    command: 'server /data --console-address ":9001"'
    environment:
      - MINIO_SERVER_URL=$MINIO_SERVER_URL
      - MINIO_BROWSER_REDIRECT_URL=$MINIO_BROWSER_REDIRECT_URL
      - MINIO_ROOT_USER=$SERVICE_USER_MINIO
      - MINIO_ROOT_PASSWORD=$SERVICE_PASSWORD_MINIO
    volumes:
      - 'minio-data:/data'
```
      
      and this works quite well actually.
